USE [master]
GO

/****** Object:  Database [TomasosIdentity]    Script Date: 2017-01-23 10:06:21 ******/
CREATE DATABASE [TomasosIdentity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tomasos', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TomasosIdentity.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tomasos_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TomasosIdentity_log.ldf' , SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TomasosIdentity] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TomasosIdentity].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TomasosIdentity] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TomasosIdentity] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TomasosIdentity] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TomasosIdentity] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TomasosIdentity] SET ARITHABORT OFF 
GO

ALTER DATABASE [TomasosIdentity] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TomasosIdentity] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TomasosIdentity] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TomasosIdentity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TomasosIdentity] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TomasosIdentity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TomasosIdentity] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TomasosIdentity] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TomasosIdentity] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TomasosIdentity] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TomasosIdentity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TomasosIdentity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TomasosIdentity] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TomasosIdentity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TomasosIdentity] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TomasosIdentity] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TomasosIdentity] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TomasosIdentity] SET RECOVERY FULL 
GO

ALTER DATABASE [TomasosIdentity] SET  MULTI_USER 
GO

ALTER DATABASE [TomasosIdentity] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TomasosIdentity] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TomasosIdentity] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TomasosIdentity] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TomasosIdentity] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TomasosIdentity] SET QUERY_STORE = OFF
GO

USE [TomasosIdentity]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TomasosIdentity] SET  READ_WRITE 
GO

